### PR TITLE
Updates the footer with facebook,email,phone(not yet updated) details

### PR DESCRIPTION
**Pull request by PrabhuKGP**
Added font-awesome icon CSS to head
added 3 columns at the footer
It will be better if the facebook logo size is made bigger, but how to do that?

### CODE REVIEW

**Comment by Shankusu993** [comment]
hey there @PrabhuKGP , thanks for the PR. You did a great job but can you just make these small changes:
* make it two-column with email, phone, FB in one column under 'contact us' as the title and the other column with the logo and name of society and institution.
* Remove the FB logo and just write 'Facebook: '
* Add MASK logo along with the full name of MASK and 'Indian Institute of Technology Kharagpur, India' 
* use `+91 9325574468` as the contact phone number and update it in the footer accordingly.
* check the alignment of the field value, the email is not properly aligned with 'email', anyway this time around make them horizontal and align all fields vertically.

**Comment by PrabhuKGP** [comment]
- Added favicon to page
- updated footer with contact details, Mask logo

**Comment by Shankusu993** [comment]
hey there @PrabhuKGP , can you just pull the current changes and resolve the merge conflict, I can then go ahead and test & merge your changes relating to the footer.

**Comment by PrabhuKGP** [comment]
Can u please tell the commands, I'm new to git

**Comment by Shankusu993** [comment]
can you remove the `made with `:heart:`  by ...` part in the footer. It's unnecessary and incorrect too.

**Comment by PrabhuKGP** [comment]
Sure

**Comment by Shankusu993** [comment]
great work @PrabhuKGP .I'm Merging it and closing the corresponding issue. You can take up more issues and start working on them. Just don't forget to assign them to yourself so that double work can be avoided.

**Pull request merged**
