### PR TITLE
added a form page

### PR DESCRIPTION
**Pull request by waleedj99**
#33 
Made a new form for Fanart submission using  Bootstrap
it currently looks like this
Screenshot_2019-12-10 MASK

### CODE REVIEW

**Comment by PrabhuKGP** [comment]
[Screenshot from Gyazo](https://gyazo.com/c03f0c904faad8c1b9856d71c8d95851)

- This is what I get when I clicked the link

**Comment by Shankusu993** [comment]
Great work @waleedj99 , also a good choice of the background too. Can you just make this small change :
- *replace the text MASK in navbar with the logo as in the index.html*

@PrabhuKGP  to test his changes you need to pull his branch and open the form.html page

**Comment by waleedj99** [comment]
Made the changes as u asked

**Comment by Shankusu993** [comment]
@waleedj99 , please resolve the conflicts for me to test the changes.

**Comment by waleedj99** [comment]
Updated the page with correct footer
Screenshot_2019-12-28 MASK(2)


Hopefully everything is correct this time

**Pull request closed without merging**
