### PR TITLE
added logo to navbar

### PR DESCRIPTION
**Pull request by 1880akshay**
I have replaced the text (MASK) with the logo in navbar and have added media queries for better mobile view of the logo.

### CODE REVIEW

**Comment by Shankusu993** [comment]
hey @1880akshay , sorry for the delayed response. Thanks for the PR.
Can you resolve this minor issue with the PR:
* In this modified version, the scroll bar starts to appear on the right side which makes the landing page less effective, try to make it not show up.

**Comment by 1880akshay** [comment]
Sorry but I am not able to understand the issue. Can you please explain in a bit clear and detailed manner?

**Comment by 1880akshay** [comment]
@Shankusu993 Can you please explain the issue so that I may work upon it ASAP?

**Comment by Shankusu993** [comment]
hey there, 
    It looks alright in current state. I merged this PR. You can move ahead with the other issues.

**Comment by 1880akshay** [comment]
Okay thanks!

**Pull request merged**
